services:
  app:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
      - MAX_USERS=${MAX_USERS}
      - ENCRYPTED_FILES_DIR=${ENCRYPTED_FILES_DIR}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - encrypted_data:/usr/src/app/${ENCRYPTED_FILES_DIR}

  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  pgdata:
  encrypted_data:
