"use client"

import { Button, Input, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, Radio, RadioGroup } from "@heroui/react"
import { Copy } from "lucide-react"
import { useId, useState } from "react"

type ShareConfirmationModalProps = {
  isOpen: boolean
  onClose: () => void
  onConfirm: (expiryMinutes: number | null) => void
  fileName: string
  /**
   * Generated by the caller when it opens this modal, so a fresh key exists per
   * share without setting state from an effect on every open.
   */
  shareKey: string
}

const EXPIRY_OPTIONS: { value: string, label: string, minutes: number | null }[] = [
  { value: "10min", label: "10 minutes", minutes: 10 },
  { value: "1hour", label: "1 hour", minutes: 60 },
  { value: "1day", label: "1 day", minutes: 60 * 24 },
  { value: "30days", label: "30 days", minutes: 60 * 24 * 30 },
  { value: "1year", label: "1 year", minutes: 60 * 24 * 365 },
  { value: "never", label: "Never expires", minutes: null },
]

export default function ShareConfirmationModal({ isOpen, onClose, onConfirm, fileName, shareKey }: ShareConfirmationModalProps) {
  const [expiry, setExpiry] = useState<string>("1day")
  const shareKeyId = useId()

  const handleConfirm = () => {
    if (!shareKey) {
      return
    }
    onConfirm(EXPIRY_OPTIONS.find((o) => o.value === expiry)?.minutes ?? null)
    onClose()
  }

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(shareKey)
    } catch (error) {
      console.error("Failed to copy share key:", error)
    }
  }

  return (
    <Modal isOpen={isOpen} onClose={onClose} scrollBehavior="inside">
      <ModalContent>
        <ModalHeader>
          Share "
          {fileName}
          "
        </ModalHeader>
        <ModalBody>
          <p className="mb-2">Choose how long this share link should be valid:</p>

          <RadioGroup value={expiry} onValueChange={setExpiry} aria-label="Share link expiry">
            {EXPIRY_OPTIONS.map((option) => (
              <Radio key={option.value} value={option.value}>
                {option.label}
              </Radio>
            ))}
          </RadioGroup>

          <div className="mt-4">
            <Input
              id={shareKeyId}
              label="Share key for this file"
              value={shareKey}
              readOnly
              size="sm"
              className="font-mono"
              description="Unique to this share. Send it to the recipient separately from the link."
              endContent={(
                <Button isIconOnly size="sm" variant="light" aria-label="Copy share key" onPress={copyToClipboard}>
                  <Copy aria-hidden="true" className="w-4 h-4" />
                </Button>
              )}
            />
            <p className="mt-2 text-warning text-xs">
              This key is never sent to the server and cannot be recovered later. Copy it now — if you lose it, delete the share and create a new one.
            </p>
          </div>
        </ModalBody>
        <ModalFooter>
          <Button variant="ghost" className="min-h-11" onPress={onClose}>
            Cancel
          </Button>
          <Button color="primary" className="min-h-11" onPress={handleConfirm} isDisabled={!shareKey}>
            Create Share Link
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  )
}
